spring.application.name=bk-payment-test
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# DevTools
spring.devtools.restart.enabled=true

# Bplay API
bpay.base-url=https://dev-biz-zero.bizplay.co.kr

# 역거래 API (비플페이 → 이용기관) 목적지
bpay.reverse-base-url=https://dev-gift.appply.co.kr
